version: '3.4'

services:
  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  #   image: localstack/localstack
  #   network_mode: bridge
  #   ports:
  #     - "4566-4599:4566-4599"
  #     - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
  #   environment:
  #     - SERVICES=sqs,lambda,dynamodb
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes: 
  #     - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  
  # localstack-setup:
  #   image: amazon/aws-cli
  #   depends_on: 
  #     - "localstack"
  #   build:
  #     context: .
  #     dockerfile: aws-stack/Dockerfile

  messagelistener:
    image: messagelistener
    build:
      context: .
      dockerfile: message-listener/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}